### PR TITLE
Initial support for scrubbers via a fluent API

### PR DESCRIPTION
**Pull request by JosephWoodward**
## This should be small

Small pull requests are great and easy for me to understand and accept
Please try prefix every commits in the pull request with  [Arlo's git notation](https://github.com/RefactoringCombos/ArlosCommitNotation/blob/master/README.md)
| Prefix | Meaning |
|--------|---------|
| e   | development enviroment only - not production|
| d   | documentation only|
| t   | tests only|
| R!! | Refactoring |
| B!! | Bug Fix |
| F!! | New Feature |

## But it's not small!

Then you should setup a remote pairing session with Llewellyn ( llewellyn.falco@gmail.com )
Usually the sessions are between 45-90 minutes.

assuming you still feel it is small, please include

## Description

This pull request adds support for scrubbers via an `approvals.Options()` API. For example:

```golang
approvals.Options().WithRegexScrubber(scrubber, "<time>")
```

## The solution

This is a new feature, so not much change needed to go into the existing API surface.

## Notation

I prefer lots of very small commits prefixed with [Arlo's git notation](https://github.com/RefactoringCombos/ArlosCommitNotation/blob/master/README.md)

### CODE REVIEW

**Comment by hjwk** [comment]
looks nice :) 

An update to the readme to document the new functionality might be useful too ?

**Comment by emilybache** [comment]
I like the look of this as well, thankyou! I know you've been discussing more with @objarni so I'll wait for his comments too.

**Comment by objarni** [comment]
I'll pair review/update this PR with @JosephWoodward when he's back from vacation.

**Comment by JosephWoodward** [comment]
@emilybache Thanks, as @objarni has mentioned, we're planning on a pair reviewing session to go through the pull request in finer detail.

**Comment by isidore** [comment]
@JosephWoodward I like a lot of this, but have some issues with the API.
I would love to schedule a time to pair on it together. I feel we could address everything and release in an hour or so.

When's good for you?

**Comment by objarni** [comment]
Not sure if this happened?

I'm available Sunday CEST9:30-11 this weekend, would that suit you @JosephWoodward ?

**Comment by emilybache** [comment]
Shall I merge this now? Is everything ready?

**Comment by objarni** [comment]
Some functions still need options argument, and we want to rewrite the VerifyWithExtension function to use options instead, deprecating it. We have scheduled another session later this week.

**Comment by objarni** [comment]
(but it is already valuable to @JosephWoodward I believe)

**Comment by JosephWoodward** [comment]
Pair programmed with @objarni  but have no updated the main documentation. Thanks @objarni for the really enjoyable pairing sessions!

**Comment by objarni** [comment]
@emilybache @isidore it seems I don't have write access to the repository so cannot merge.

**Comment by objarni** [comment]
@JosephWoodward thanks for contributing and fun pair programming sessions!

**Comment by emilybache** [comment]
Thankyou so much for this! Looks great.

**Pull request merged**
